language: ruby
rvm:
- 2.3.6
- 2.4.3
- 2.5.0
script: bundle exec rspec spec/unit
addons:
  code_climate:
    repo_token:
      secure: x4ET3gWdfwTC66ExUDoYFdJ3AvCTbms7dokF7RaUrf7xnr3PInHnRgzZP7hICkEYW4t20JPjwiJUUdifk5XUcMSlQ5AAPKjFXP4wyQYPvpizI5FvRsX0a62/Fv1juXxs9hPFmXITqN861iT1rkqC383evyR9KxPDZMOi0VEOjAs=
after_success:
  - bundle exec codeclimate-test-reporter
