categories:
- name: Type
  labels:
  - color: f9eea7
    description: 'Issue in existing functionality'
    id: 1181821042a
    name: Bug
  - color: f9eea7
    description: 'New functionality'
    id: 1181821042b
    name: Feature
  - color: f9eea7
    description: 'Improvement of code without user-visible changes'
    id: 1181821042
    name: Refactoring
- name: Categories
  labels:
  - color: 039634
    description: 'Command Line Interface'
    id: 1181821630
    name: CLI
  - color: 52e59e
    description: 'Inqlude data, including schema and content'
    id: 1181823572
    name: Data
  - color: cdffa5
    description: ''
    id: 1181820759
    name: Documentation
  - color: 009800
    description: 'Inqlude web site'
    id: 60095012
    name: Web Site
- name: Priorities
  labels:
  - color: fbca04
    description: ''
    id: 120813816
    name: Low Priority
  - color: eb6420
    description: ''
    id: 120813794
    name: Medium Priority
  - color: e11d21
    description: ''
    id: 120813779
    name: High Priority
- name: Welcome
  labels:
  - color: 5319e7
    description: 'good issue to start with if you are new to the project'
    id: 761165516
    name: good first issue
  - color: b60205
    description: 'possible task or project for GSoC'
    id: 395340299
    name: GSoC
org: cornelius
repo: inqlude
